import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { notifications as seedNotifications } from "../data/notifications-shim";
import { findMode } from "../data/gameMeta";
import { supabase } from "../lib/supabase";
import { useAuth } from "./AuthContext";

// NOTE on scope: notifications has no backing table in the Supabase schema yet, so it stays on local seed data.
const DataContext = createContext(null);
const WIN_POINTS = 3;
const KILL_POINTS = 1;

function mapTournament(row, confirmedCounts) {
  return { id: row.id, name: row.name, game: row.game, mode: row.mode, teamSize: row.team_size, host: row.host, organizer: row.host, banner: "linear-gradient(135deg,#1a0b2e,#0b0e16 60%)", description: row.description, entryFee: Number(row.entry_fee), prizePool: Number(row.prize_pool), prizeSplit: { first: Number(row.first_prize), second: Number(row.second_prize), third: Number(row.third_prize) }, maxTeams: row.max_teams, registeredTeams: confirmedCounts[row.id] ?? 0, registrationDeadline: row.registration_deadline, startDate: row.start_date, status: row.status, rules: row.rules || [], roomId: row.room_id, roomPassword: row.room_password };
}
function mapPlayer(row) { return { id: row.id, userId: row.user_id, name: row.player_name, gameUid: row.game_uid, ign: row.ign, substitute: row.is_substitute }; }
function mapTeamBase(row, playerRows, registrationRows, profileNameById) { const ownRegistrations = registrationRows.filter((r) => r.team_id === row.id); return { id: row.id, name: row.name, tag: row.tag, college: row.college, captainUserId: row.captain_id, captain: profileNameById[row.captain_id] || "", logo: "🎮", players: playerRows.filter((p) => p.team_id === row.id).map(mapPlayer), tournamentIds: ownRegistrations.map((r) => r.tournament_id), registrationStatus: ownRegistrations[0]?.status || "confirmed" }; }
function mapPayment(row, regById) { const reg = regById[row.registration_id]; return { id: row.id, registrationId: row.registration_id, teamId: reg?.team_id, tournamentId: reg?.tournament_id, amount: Number(row.amount), utr: row.utr, payerUpi: row.payer_upi, status: row.status, createdAt: row.submitted_at }; }
function mapPayout(row) { return { id: row.id, tournamentId: row.tournament_id, placement: row.placement, recipient: row.recipient_name, upiId: row.recipient_upi, amount: Number(row.amount), status: row.status, paidAt: row.paid_at }; }
function formatMatchDate(scheduledAt) { if (!scheduledAt) return { date: "", time: "" }; const d = new Date(scheduledAt); return { date: d.toISOString().slice(0, 10), time: d.toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" }) }; }
function mapMatch(row, teamNameById) { const { date, time } = formatMatchDate(row.scheduled_at); return { id: row.id, tournamentId: row.tournament_id, round: row.round, matchNumber: row.match_number, teamAId: row.team_a_id, teamBId: row.team_b_id, teamA: (row.team_a_id && teamNameById[row.team_a_id]) || row.team_a_label || "TBD", teamB: (row.team_b_id && teamNameById[row.team_b_id]) || row.team_b_label || "TBD", scoreA: row.score_a, scoreB: row.score_b, killsA: row.kills_a, killsB: row.kills_b, winnerTeamId: row.winner_team_id, status: row.status, resultNotes: row.result_notes || "", resultEvidenceUrl: row.result_evidence_url || "", resultLockedAt: row.result_locked_at || null, resultLockedBy: row.result_locked_by || null, scheduledAt: row.scheduled_at, roomId: row.room_id, roomPassword: row.room_password, date, time }; }
function computeTeamStats(teamId, matchRows) { const played = matchRows.filter((m) => m.status === "completed" && (m.team_a_id === teamId || m.team_b_id === teamId)); const wins = played.filter((m) => m.winner_team_id === teamId).length; const kills = played.reduce((sum, m) => { if (m.team_a_id === teamId) return sum + (m.kills_a || 0); if (m.team_b_id === teamId) return sum + (m.kills_b || 0); return sum; }, 0); return { matches: played.length, wins, kills, points: wins * WIN_POINTS + kills * KILL_POINTS }; }

export function DataProvider({ children }) {
  const { user } = useAuth();
  const [tournaments, setTournaments] = useState([]); const [teamsBase, setTeamsBase] = useState([]); const [matchesRaw, setMatchesRaw] = useState([]); const [notifications, setNotifications] = useState(seedNotifications); const [payments, setPayments] = useState([]); const [payouts, setPayouts] = useState([]); const [announcements, setAnnouncements] = useState([]); const [reports, setReports] = useState([]);
  const refreshTournaments = useCallback(async () => { const [{ data: rows, error }, { data: counts }] = await Promise.all([supabase.from("tournaments").select("*").order("created_at", { ascending: false }), supabase.rpc("tournament_team_counts")]); if (error) { console.error(error.message); return; } const countMap = {}; (counts || []).forEach((c) => { countMap[c.tournament_id] = Number(c.confirmed_teams); }); setTournaments((rows || []).map((row) => mapTournament(row, countMap))); }, []);
  const refreshTeams = useCallback(async () => { const [{ data: teamRows, error }, { data: playerRows }, { data: registrationRows }, { data: profileRows }] = await Promise.all([supabase.from("teams").select("*"), supabase.from("team_players").select("*"), supabase.from("registrations").select("*"), supabase.from("profiles").select("id, full_name")]); if (error) { console.error(error.message); return; } const profileNameById = Object.fromEntries((profileRows || []).map((p) => [p.id, p.full_name])); setTeamsBase((teamRows || []).map((row) => mapTeamBase(row, playerRows || [], registrationRows || [], profileNameById))); }, []);
  const refreshMatches = useCallback(async () => { const [{ data, error }, { data: roomRows, error: roomError }] = await Promise.all([user?.role === "admin" ? supabase.from("matches").select("*").order("scheduled_at", { ascending: true }) : supabase.from("match_public").select("*").order("scheduled_at", { ascending: true }), user ? supabase.from("match_rooms").select("match_id, room_id, room_password") : Promise.resolve({ data: [], error: null })]); if (error) { console.error(error.message); return; } if (roomError) console.error(roomError.message); const rooms = Object.fromEntries((roomRows || []).map((r) => [r.match_id, r])); setMatchesRaw((data || []).map((row) => ({ ...row, room_id: rooms[row.id]?.room_id ?? null, room_password: rooms[row.id]?.room_password ?? null }))); }, [user]);
  const refreshPayments = useCallback(async () => { const [{ data: payRows, error }, { data: regRows }] = await Promise.all([supabase.from("payments").select("*").order("submitted_at", { ascending: false }), supabase.from("registrations").select("id, team_id, tournament_id")]); if (error) { console.error(error.message); return; } const regById = Object.fromEntries((regRows || []).map((r) => [r.id, r])); setPayments((payRows || []).map((row) => mapPayment(row, regById))); }, []);
  const refreshPayouts = useCallback(async () => { const { data, error } = await supabase.from("payouts").select("*").order("created_at", { ascending: false }); if (error) { console.error(error.message); return; } setPayouts((data || []).map(mapPayout)); }, []);
  const refreshReports = useCallback(async () => { if (!user) { setReports([]); return; } const { data, error } = await supabase.from("reports").select("*").order("created_at", { ascending: false }); if (error) { console.error(error.message); return; } setReports(data || []); }, [user]);
  const refreshAnnouncements = useCallback(async () => { const { data, error } = await supabase.from("announcements").select("*").order("created_at", { ascending: false }); if (error) { console.error(error.message); return; } setAnnouncements((data || []).map((row) => ({ id: row.id, tournamentId: row.tournament_id, title: row.title, message: row.message, createdAt: row.created_at }))); }, []);
  useEffect(() => { refreshTournaments(); }, [refreshTournaments]); useEffect(() => { refreshAnnouncements(); }, [refreshAnnouncements]); useEffect(() => { refreshReports(); }, [refreshReports]);
  useEffect(() => { const channel = supabase.channel("arena-live").on("postgres_changes", { event: "*", schema: "public", table: "matches" }, () => refreshMatches()).on("postgres_changes", { event: "*", schema: "public", table: "announcements" }, () => refreshAnnouncements()).on("postgres_changes", { event: "*", schema: "public", table: "reports" }, () => refreshReports()).subscribe(); return () => { supabase.removeChannel(channel); }; }, [refreshMatches, refreshAnnouncements, refreshReports]);
  useEffect(() => { refreshTeams(); }, [user, refreshTeams]); useEffect(() => { refreshMatches(); }, [refreshMatches]); useEffect(() => { if (user) { refreshPayments(); if (user.role === "admin") refreshPayouts(); } else { setPayments([]); setPayouts([]); } }, [user, refreshPayments, refreshPayouts]);
  const teamNameById = useMemo(() => Object.fromEntries(teamsBase.map((t) => [t.id, t.name])), [teamsBase]); const matches = useMemo(() => matchesRaw.map((row) => mapMatch(row, teamNameById)), [matchesRaw, teamNameById]); const teams = useMemo(() => teamsBase.map((t) => ({ ...t, ...computeTeamStats(t.id, matchesRaw) })), [teamsBase, matchesRaw]);
  const notify = (text) => setNotifications((prev) => [{ id: `n${Date.now()}`, text, time: "Just now", read: false }, ...prev]);
  const submitReport = async (matchId, category, subject, description) => { if (!user) throw new Error("Please log in to submit a report."); if (!subject?.trim() || !description?.trim()) throw new Error("Add a subject and description."); const match = matches.find((m) => m.id === matchId); const { error } = await supabase.from("reports").insert({ match_id: matchId || null, tournament_id: match?.tournamentId || null, reporter_id: user.id, category: category || "other", subject: subject.trim(), description: description.trim() }); if (error) throw new Error(error.message); await refreshReports(); notify("Your report was submitted to tournament administration."); };
  const updateReport = async (reportId, status, adminNote = "") => { if (user?.role !== "admin") throw new Error("Only administrators can manage reports."); const { error } = await supabase.from("reports").update({ status, admin_note: adminNote, resolved_by: status === "resolved" ? user.id : null, updated_at: new Date().toISOString() }).eq("id", reportId); if (error) throw new Error(error.message); await refreshReports(); };
  const registerTeam = async (tournamentId, teamData) => { if (!user) throw new Error("Please log in before registering a team."); const tournament = tournaments.find((t) => t.id === tournamentId); if (!tournament) throw new Error("Tournament not found."); if (tournament.status !== "open" && tournament.status !== "starting_soon") throw new Error("This tournament is not accepting registrations."); if (tournament.registrationDeadline && new Date(tournament.registrationDeadline + "T23:59:59") < new Date()) throw new Error("The registration deadline has passed."); const mainRosterCount = teamData.players.filter((p) => !p.substitute).length; if (mainRosterCount !== tournament.teamSize) throw new Error(`This tournament's mode (${tournament.mode}) needs exactly ${tournament.teamSize} player${tournament.teamSize > 1 ? "s" : ""} per team.`); const tag = teamData.teamName.trim().slice(0, 3).toUpperCase() || "TM"; const { data: team, error: teamError } = await supabase.from("teams").insert({ name: teamData.teamName.trim(), tag, college: teamData.college?.trim() || "Open", captain_id: user.id }).select().single(); if (teamError) throw new Error(teamError.message.includes("duplicate") ? "You already have a team with that name — pick a different name." : teamError.message.message || teamError.message); const playerRows = teamData.players.map((p) => ({ team_id: team.id, player_name: p.name, game_uid: p.gameUid, ign: p.ign, is_substitute: Boolean(p.substitute) })); const { error: playersError } = await supabase.from("team_players").insert(playerRows); if (playersError) throw new Error(playersError.message); const status = Number(tournament.entryFee) > 0 ? "payment_pending" : "confirmed"; const { data: registration, error: regError } = await supabase.from("registrations").insert({ tournament_id: tournamentId, team_id: team.id, status, accepted_terms_at: new Date().toISOString() }).select().single(); if (regError) throw new Error(regError.message); await refreshTeams(); if (status === "confirmed") await refreshTournaments(); notify(`Your team "${team.name}" registration was successful.`); return { id: team.id, name: team.name, registrationId: registration.id, registrationStatus: registration.status }; };
  const submitPayment = async (tournamentId, teamId, details) => { const tournament = tournaments.find((t) => t.id === tournamentId); if (!tournament || !details.utr?.trim()) throw new Error("Enter the UPI transaction reference."); const { data: registration, error: regError } = await supabase.from("registrations").select("id").eq("tournament_id", tournamentId).eq("team_id", teamId).single(); if (regError || !registration) throw new Error("Registration not found."); const { data: payment, error } = await supabase.from("payments").insert({ registration_id: registration.id, amount: tournament.entryFee, provider: "upi_manual", utr: details.utr.trim(), payer_upi: details.payerUpi?.trim() }).select().single(); if (error) throw new Error(error.message.includes("duplicate") ? "That UPI transaction reference has already been submitted." : error.message); await refreshPayments(); notify(`UPI payment submitted for review for ${tournament.name}.`); return { id: payment.id, teamId, tournamentId, amount: Number(payment.amount), utr: payment.utr, status: payment.status }; };
  const reviewPayment = async (paymentId, approved) => { if (user?.role !== "admin") throw new Error("Only administrators can review payments."); const { data: payment, error: fetchError } = await supabase.from("payments").select("*").eq("id", paymentId).single(); if (fetchError || !payment) throw new Error("Payment not found."); if (payment.status !== "pending") return; const status = approved ? "approved" : "rejected"; const { error } = await supabase.from("payments").update({ status, reviewed_at: new Date().toISOString(), reviewed_by: user.id }).eq("id", paymentId); if (error) throw new Error(error.message); const { error: regUpdateError } = await supabase.from("registrations").update({ status: approved ? "confirmed" : "rejected" }).eq("id", payment.registration_id); if (regUpdateError) throw new Error(regUpdateError.message); await Promise.all([refreshPayments(), refreshTeams(), refreshTournaments()]); };
  const recordPayout = async (tournamentId, placement, recipient, upiId, amount) => { if (user?.role !== "admin") throw new Error("Only administrators can record payouts."); if (!recipient?.trim() || !upiId?.trim() || !Number(amount)) throw new Error("Recipient, UPI ID, and payout amount are required."); const tournament = tournaments.find((t) => t.id === tournamentId); const paidSoFar = payouts.filter((p) => p.tournamentId === tournamentId).reduce((sum, p) => sum + p.amount, 0); if (tournament && paidSoFar + Number(amount) > tournament.prizePool) throw new Error("Payout exceeds the advertised prize pool."); const { data, error } = await supabase.from("payouts").insert({ tournament_id: tournamentId, placement: placement?.trim() || "Prize", recipient_name: recipient.trim(), recipient_upi: upiId.trim(), amount: Number(amount), status: "paid", paid_at: new Date().toISOString(), recorded_by: user.id }).select().single(); if (error) throw new Error(error.message); await refreshPayouts(); return mapPayout(data); };
  const updateTournamentRoom = async (tournamentId, roomId, roomPassword) => { if (user?.role !== "admin") throw new Error("Only administrators can update tournament credentials."); const { error } = await supabase.from("tournaments").update({ room_id: roomId?.trim() || null, room_password: roomPassword?.trim() || null, updated_at: new Date().toISOString() }).eq("id", tournamentId); if (error) throw new Error(error.message); await refreshTournaments(); };
  const deleteTournament = async (tournamentId) => { if (user?.role !== "admin") throw new Error("Only administrators can delete tournaments."); const { error } = await supabase.rpc("admin_delete_tournament", { p_tournament_id: tournamentId }); if (error) throw new Error(error.message); await Promise.all([refreshTournaments(), refreshTeams(), refreshMatches(), refreshPayments(), refreshPayouts()]); };
  const updateTournament = async (tournamentId, data) => { if (user?.role !== "admin") throw new Error("Only administrators can edit tournaments."); const mode = findMode(data.game, data.mode); if (!mode) throw new Error("Choose a valid game mode."); const prizePool = Number(data.prizePool) || 0; const { error } = await supabase.from("tournaments").update({ name: data.name.trim(), game: data.game, mode: data.mode, team_size: mode.teamSize, host: data.host?.trim() || "Arena Clash", description: data.description?.trim() || "", entry_fee: Number(data.entryFee) || 0, prize_pool: prizePool, first_prize: Number(data.firstPrize) || 0, second_prize: Number(data.secondPrize) || 0, third_prize: Number(data.thirdPrize) || 0, max_teams: Number(data.maxTeams) || 0, registration_deadline: data.registrationDeadline || null, start_date: data.startDate || null, status: data.status || "open", rules: data.rules || [] }).eq("id", tournamentId); if (error) throw new Error(error.message); await refreshTournaments(); };
  const createTournament = async (data) => { if (user?.role !== "admin") throw new Error("Only administrators can create tournaments."); const mode = findMode(data.game, data.mode); if (!mode) throw new Error("Choose a valid game mode."); const prizePool = Number(data.prizePool) || 0; const { data: row, error } = await supabase.from("tournaments").insert({ name: data.name.trim(), game: data.game, mode: data.mode, team_size: mode.teamSize, host: data.host?.trim() || "Arena Clash", description: data.description?.trim() || "", entry_fee: Number(data.entryFee) || 0, prize_pool: prizePool, first_prize: Number(data.firstPrize) || 0, second_prize: Number(data.secondPrize) || 0, third_prize: Number(data.thirdPrize) || 0, max_teams: Number(data.maxTeams) || 0, registration_deadline: data.registrationDeadline || null, start_date: data.startDate || null, status: data.status || "open", rules: data.rules || [] }).select().single(); if (error) throw new Error(error.message); await refreshTournaments(); return row; };
  const createMatch = async (data) => { if (user?.role !== "admin") throw new Error("Only administrators can create matches."); const { data: row, error } = await supabase.from("matches").insert({ tournament_id: data.tournamentId, round: data.round, match_number: Number(data.matchNumber), team_a_id: data.teamAId || null, team_b_id: data.teamBId || null, team_a_label: data.teamALabel?.trim() || null, team_b_label: data.teamBLabel?.trim() || null, scheduled_at: data.scheduledAt || null, status: data.status || "scheduled", room_id: null, room_password: null }).select().single(); if (error) throw new Error(error.message); await refreshMatches(); return mapMatch(row, teamNameById); };
  const updateMatch = async (matchId, data) => { if (user?.role !== "admin") throw new Error("Only administrators can update matches."); const { error } = await supabase.from("matches").update({ round: data.round, match_number: Number(data.matchNumber), team_a_id: data.teamAId || null, team_b_id: data.teamBId || null, team_a_label: data.teamALabel?.trim() || null, team_b_label: data.teamBLabel?.trim() || null, scheduled_at: data.scheduledAt || null, status: data.status || "scheduled" }).eq("id", matchId); if (error) throw new Error(error.message); await refreshMatches(); };
  const updateMatchResult = async (matchId, data) => { if (user?.role !== "admin") throw new Error("Only administrators can update match results."); const { error } = await supabase.from("matches").update({ score_a: Number(data.scoreA) || 0, score_b: Number(data.scoreB) || 0, kills_a: Number(data.killsA) || 0, kills_b: Number(data.killsB) || 0, winner_team_id: data.winnerTeamId || null, result_notes: data.resultNotes?.trim() || null, result_evidence_url: data.resultEvidenceUrl?.trim() || null, status: "completed", result_locked_at: new Date().toISOString(), result_locked_by: user.id }).eq("id", matchId); if (error) throw new Error(error.message); await refreshMatches(); await refreshTeams(); };
  const updateMatchRoom = async (matchId, roomId, roomPassword) => { if (user?.role !== "admin") throw new Error("Only administrators can update match rooms."); const { error } = await supabase.from("match_rooms").upsert({ match_id: matchId, room_id: roomId?.trim() || null, room_password: roomPassword?.trim() || null, updated_at: new Date().toISOString() }, { onConflict: "match_id" }); if (error) throw new Error(error.message); await refreshMatches(); };
  const markNotificationsRead = () => setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  return <DataContext.Provider value={{ tournaments, teams, matches, notifications, payments, payouts, announcements, reports, createTournament, updateTournament, deleteTournament, registerTeam, submitPayment, reviewPayment, recordPayout, updateTournamentRoom, createMatch, updateMatch, updateMatchResult, updateMatchRoom, submitReport, updateReport, markNotificationsRead }}>{children}</DataContext.Provider>;
}
export function useData() { return useContext(DataContext); }
